### ISSUE TITLE
Add support for git dependencies

### ISSUE THREAD

**Issue by SamLebarbare** [Xcraft-Inc/startcraft#3]
When we have a git dep. in package.json, the Semver check fail, because the module is not specifing a version.

`  "mydep": "git://github.com/user/mydep.git#94abb69"`

we need to fix the helper

> helpers.isSemverSatisfies (s)

this format can be valid:
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by Skywalker13** [comment]
Yes but IMHO it's a very bad habit to pass a git repository instead of npmjs packages. Why are you using a repository?

**Comment by Skywalker13** [comment]
Note that if it's really necessary, you can add this dependency as submodule + in `.scrc`.

**Comment by SamLebarbare** [comment]
@Skywalker13 i'am waiting for an integrating pullrequest, and i want tempory use my repository version for testing.
